version: "3"
services:
  app:
    build: .
    container_name: app
    env_file:
      - .env
    volumes:
      - ./.decodex/:/root/.decodex/:rw
      - ./.chainlit:/app/.chainlit:rw
    ports:
      - "8000:8000"
