version: "3"
services:
  app:
    build: .
    container_name: decodex-ui
    env_file:
      - .env
    volumes:
      - ./.decodex/:/root/.decodex/:rw
      - ./.chainlit:/app/.chainlit:rw
    ports:
      - "${DECODEX_UI_PORT}:${DECODEX_UI_PORT}"
